---
- #list of items in python
  hosts: all 

  tasks:
    - name: update my ubuntu system 
      ansible.builtin.apt:
        update_cache: yes
    - name: Install apache httpd  (state=present is optional)
      ansible.builtin.apt:
        name: default-jdk
        state: present
